server:
    port: 9000
    ssl:
        key-store: classpath:keystore.p12
        key-store-password: transcode
        key-store-type: PKCS12
        key-alias: tomcat
        key-store-provider: SunJSSE

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/transcode
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
    data:
        rest:
            base-path: /api
    resources:
        chain:
            enabled: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: adigo.axel@gmail.com
        password: joelindien01
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
security:
  oauth2:
    client:
      clientId: 977379455702407
      clientSecret: 8d9a844a84fd60a2e20f3caf566fe728
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
multipart:
    maxFileSize: 10247578KB
    maxRequestSize: 10247578KB